# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - checkout: self

  - script: python -m pip install --upgrade pip tox wheel
    displayName: 'Install tools'

  - task: Cache@2
    inputs:
      key: 'python | "$(Agent.OS)" | requirements.txt'
      restoreKeys: | 
        python | "$(Agent.OS)"
        python
      path: $(PIP_CACHE_DIR)
    displayName: Cache pip packages

  - script: pip install -r requirements.txt
    displayName: 'Install dependencies'

 # - script: |
 ##     echo Add other tasks to build, test, and deploy your project.
  #    echo `env`
  #    echo "Variable " + $GIT_REPO + $GIT_BRANCH
  #  displayName: 'Run a multi-line script'
